# file: roles/shinken/tasks/main.yaml

- import_tasks: install.yaml
  tags:
    - shinken

- import_tasks: configure.yaml
  tags:
    - shinken

- import_tasks: webui.yaml
  tags:
    - shinken

- import_tasks: commands.yaml
  tags:
    - shinken

- import_tasks: services.yaml
  tags:
    - shinken
